[tool.ruff]
# Set the minimum Python version to target for fixes.
target-version = "py311"

[tool.ruff.lint]
# Enable the specified rule codes.
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle (Errors)
    "W",  # pycodestyle (Warnings)
    "I",  # isort
    "B",  # flake8-bugbear
]
# Never enforce line length when using the formatter.
ignore = ["E501"]

# Allow autofix for all enabled rules.
fixable = ["ALL"]

[tool.ruff.format]
# Enable the formatter.
# Uses a Black-compatible style by default.
quote-style = "double"